image: python:latest


linting:
  script:
    - pip3 install flake8
    - flake8 .

database-building:
  script:
    - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod 755 /usr/local/bin/docker-compose
    - cd storage/postgres
    - /usr/local/bin/docker-compose build
