image: docker:latest

stages:
  - linting
  - unittesting
# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - git config --global http.sslVerify false

linting:
  stage: linting
  image: python:latest
  script:
    - pip3 install flake8
    - flake8 .

unittesting:
  tags:
    - pi
  stage: unittesting
  image: python:latest
  script:
    - pip3 install pyyaml
    - pip3 install RPi.GPIO
    - pip3 install structlog
    - pip3 install numpy
    - apt-get install git
    - git clone https://github.com/PrzemoF/bmp183.git
    - git clone git://gist.github.com/3151375.git
    - git clone https://github.com/adafruit/Adafruit_Python_DHT.git
    - cd station-code
    - python3 test_collectweather.py -v
