---
# An employee record
name: Example Developer
job: Developer
skill: Elite
employed: True
foods:
   - Appl
   - Orange
   - Strawberry
   - Mango
languages:
   ruby: Elite
   python: Elite
   dotnet: Lame
